# Generated by Django 4.1.4 on 2023-01-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindPeople',
            fields=[
                ('post_code', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=128)),
                ('post_con', models.TextField()),
            ],
            options={
                'db_table': 'find_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegitData',
            fields=[
                ('res_code', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'regit_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('team_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'team_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=50)),
                ('user_admin', models.IntegerField()),
                ('login_state', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_back.userdata')),
            ],
            options={
                'db_table': 'user_team',
                'managed': False,
            },
        ),
    ]
