# Generated by Django 4.1.4 on 2023-01-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_cont', models.CharField(max_length=1024)),
                ('comment_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('contents_data', models.TextField(blank=True, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamUserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_back.userdata')),
                ('is_admin', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'team_user_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FindPeople',
        ),
        migrations.DeleteModel(
            name='RegitData',
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
