# Generated by Django 4.1.4 on 2023-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_back', '0002_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebBackProfilePhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_photo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'web_back_profile_photo',
                'managed': False,
            },
        ),
    ]
