# Generated by Django 4.1.4 on 2023-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_back', '0002_profile_photo_team_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_file',
            name='post',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
