# Generated by Django 4.1.4 on 2023-01-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_back', '0003_webbackprofilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('post_contents', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('post_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'team_post',
                'managed': False,
            },
        ),
    ]
